---
- hosts: 
    - vertica
  become: true
  any_errors_fatal: True
  roles:
    - { role: vertica-exporter, tags: [vertica, vertica-exporter] }

  vars:

    vertica_exporter_user: dbadmin
    vertica_exporter_pass: dbpassword
    vertica_exporter_port: 5433
    vertica_exporter_listen: "0.0.0.0:9187"


